name: Android Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

#      - name: Upload Release APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: Release APK
#          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
#
#      - name: Download Release APK
#        uses: actions/download-artifact@v2
#        with:
#          name: Release APK
#          path: downloads

      - name: Rename APK file
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/outputs/apk/release/my-app-release-v1.0.0.apk    

      - name: Generate Release Tag
        id: tag
        run: |
          echo "::set-output name=release_tag::APP_$(date +"%Y.%m.%d_%H-%M")"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: app/build/outputs/apk/release/*.apk